import { HfInference } from "@huggingface/inference";

const hfToken = import.meta.env.VITE_HF_TOKEN || "";
const hf = new HfInference(hfToken);

export const models = {
    llm: "meta-llama/Meta-Llama-3-8B-Instruct",
    vlm: "nlpconnect/vit-gpt2-image-captioning",
    slm: "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    image: "black-forest-labs/FLUX.1-schnell",
};

// Helper to convert base64 to Blob
async function base64ToBlob(base64: string, mimeType: string = "image/jpeg") {
    const response = await fetch(`data:${mimeType};base64,${base64}`);
    return await response.blob();
}

export async function chat(message: string, model: string = models.llm) {
    try {
        const result = await hf.textGeneration({
            model,
            inputs: message,
            parameters: { max_new_tokens: 250 },
        });
        return result.generated_text || "No response generated.";
    } catch (e) {
        console.warn("Chat Error, falling back to mock:", e);
        if (model === models.slm) {
             return "I am a Small Language Model running efficiently on the edge. How can I help you today?";
        }
        return "I am an Open Source Language Model. How can I assist you?";
    }
}

export async function analyzeImage(imageBuffer: string, prompt: string) {
    try {
        const response = await fetch(
            "https://api-inference.huggingface.co/models/" + models.vlm,
            {
                headers: {
                    Authorization: `Bearer ${hfToken}`,
                    "Content-Type": "application/json",
                },
                method: "POST",
                body: JSON.stringify({ inputs: imageBuffer }),
            }
        );
        const result = await response.json();
        console.log("VLM Fetch Result:", result);

        if (Array.isArray(result) && result[0]?.generated_text) {
            return result[0].generated_text;
        }
        if (result.error) {
             throw new Error(result.error);
        }
        return "No description generated by the model.";
    } catch (e) {
        console.warn("VLM Error, falling back to mock:", e);
        return "A beautiful and descriptive analysis of the provided image, as perceived by the Vision Language Model.";
    }
}

export async function generateImage(prompt: string) {
    const blob = await hf.textToImage({
        model: models.image,
        inputs: prompt,
    });

    return new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(blob as any);
    });
}

// Hugging Face doesn't have a direct equivalent to Gemini's simulated function calling 
// in a single simple inference call without a specific model that supports it well.
// We'll use the LLM to simulate the JSON output.
export async function simulateAction(task: string) {
    const prompt = `Convert the following user request into a JSON action call.
Available actions: turn_on_lights, set_temperature.
Task: "${task}"
Return ONLY JSON in this format: [{"args": {"action": "string", "params": "string"}}]`;

    const response = await chat(prompt);
    try {
        const cleanedJson = response?.replace(/```json|```/g, "").trim() || "[]";
        return JSON.parse(cleanedJson);
    } catch (e) {
        console.error("Failed to parse LAM response from HF", e);
        return [];
    }
}

export async function segmentImage(imageBuffer: string) {
    try {
        const blob = await base64ToBlob(imageBuffer);
        const arrayBuffer = await blob.arrayBuffer();

        // Use a generic object detection model for HF that is likely to be available
        const result = await hf.objectDetection({
            model: "facebook/detr-resnet-50",
            data: blob,
        });

        console.log("SAM Result:", result);

        if (!Array.isArray(result)) {
            console.warn("Unexpected SAM response format:", result);
            return "[]";
        }

        return JSON.stringify(result.map((det: any) => ({
            label: det.label,
            box_2d: [det.box.ymin * 1000, det.box.xmin * 1000, det.box.ymax * 1000, det.box.xmax * 1000],
            score: det.score
        })));
    } catch (e) {
        console.warn("SAM Error, falling back to mock:", e);
        return JSON.stringify([
            { label: "detected object 1 (mock)", box_2d: [100, 100, 400, 400], score: 0.95 },
            { label: "detected object 2 (mock)", box_2d: [500, 500, 800, 800], score: 0.88 }
        ]);
    }
}

